// Shared Event Data Array
const eventsData = [
    {
        id: 1,
        title: "Global Tech Summit 2026",
        category: "tech",
        categoryName: "Technology",
        price: 299,
        date: "2026-10-12T09:00:00",
        icon: "fa-solid fa-laptop-code",
        location: "San Francisco, CA",
        venue: "Moscone Center South",
        organizer: "TechCorp Global",
        ticketsLeft: 45,
        gradient: "linear-gradient(135deg, #818cf8, #a78bfa)",
        description: "Explore the next horizon of digital innovation. The Global Tech Summit features world-renowned keynote speakers, immersive hands-on workshops, and dedicated networking zones covering AI, Next-Gen Web, and cloud native technologies."
    },
    {
        id: 2,
        title: "Sunset Music Festival",
        category: "music",
        categoryName: "Music",
        price: 89,
        date: "2026-11-04T18:30:00",
        icon: "fa-solid fa-guitar",
        location: "Austin, TX",
        venue: "Zilker Waterfront Stage",
        organizer: "Sunset Waves Co.",
        ticketsLeft: 12,
        gradient: "linear-gradient(135deg, #f472b6, #fb7185)",
        description: "Join us for the autumn's premier outdoor music festival. Sunset Music Festival brings together highly acclaimed indie rock bands, visual electronic musicians, and local folk soloists under a gorgeous twilight sky."
    },
    {
        id: 3,
        title: "Creative Palette Workshop",
        category: "art",
        categoryName: "Arts & Design",
        price: 45,
        date: "2026-12-18T14:00:00",
        icon: "fa-solid fa-palette",
        location: "New York, NY",
        venue: "Chelsea Art Studios",
        organizer: "Artistry Guild",
        ticketsLeft: 25,
        gradient: "linear-gradient(135deg, #34d399, #60a5fa)",
        description: "Unlock your visual arts potential. Under the guidance of professional abstract painters, you will learn spatial layouts, acrylic blending techniques, and create your own premium canvas work to take home."
    },
    {
        id: 4,
        title: "AI & Robotics Exposition",
        category: "tech",
        categoryName: "Technology",
        price: 150,
        date: "2026-10-25T10:00:00",
        icon: "fa-solid fa-robot",
        location: "Boston, MA",
        venue: "MIT Innovation Pavilion",
        organizer: "Robotics Syndicate",
        ticketsLeft: 8,
        gradient: "linear-gradient(135deg, #a78bfa, #c084fc)",
        description: "An interactive showcase of state-of-the-art robotic creations, neural network configurations, and automation systems designed to shape manufacturing, healthcare, and software operations."
    },
    {
        id: 5,
        title: "Acoustic Jazz & Wine Night",
        category: "music",
        categoryName: "Music",
        price: 65,
        date: "2026-09-15T19:00:00",
        icon: "fa-solid fa-music",
        location: "New Orleans, LA",
        venue: "The Oakwood Lounge",
        organizer: "Jazz & Co.",
        ticketsLeft: 30,
        gradient: "linear-gradient(135deg, #c084fc, #6366f1)",
        description: "Wind down with an intimate evening of live acoustic jazz and vintage wine selections. Featuring classic saxophone quintets and outstanding solo pianists playing your favorite traditional arrangements."
    },
    {
        id: 6,
        title: "Morning Yoga & Zen Retreat",
        category: "sports",
        categoryName: "Sports & Wellness",
        price: 0,
        date: "2026-08-20T07:00:00",
        icon: "fa-solid fa-spa",
        location: "Denver, CO",
        venue: "Rocky Ridge Botanical Garden",
        organizer: "Zen Health Alliance",
        ticketsLeft: 50,
        gradient: "linear-gradient(135deg, #38bdf8, #34d399)",
        description: "Align your body and breath in a breathtaking mountain garden environment. This session covers core yoga flow, breathwork, and deep guided meditation. All skill levels welcome, yoga mat provided."
    },
    {
        id: 7,
        title: "UI/UX Design Masterclass",
        category: "art",
        categoryName: "Arts & Design",
        price: 120,
        date: "2026-09-30T09:30:00",
        icon: "fa-solid fa-pen-nib",
        location: "Chicago, IL",
        venue: "Downtown Design Center",
        organizer: "Pixel Academy",
        ticketsLeft: 18,
        gradient: "linear-gradient(135deg, #fb923c, #fb7185)",
        description: "Deep dive into web interfaces, user psychology, information mapping, and wireframing tools. Create a complete, functional prototype of a mobile app under the direction of Senior Designers."
    },
    {
        id: 8,
        title: "Charity 10K Running Run",
        category: "sports",
        categoryName: "Sports & Wellness",
        price: 25,
        date: "2026-08-05T06:00:00",
        icon: "fa-solid fa-person-running",
        location: "Seattle, WA",
        venue: "Alki Beach Walkway",
        organizer: "Hope Foundation",
        ticketsLeft: 120,
        gradient: "linear-gradient(135deg, #fb7185, #f472b6)",
        description: "Lace up your running shoes and join our yearly run to raise money for pediatric healthcare research. Includes marathon swag bags, runner tags, and custom finisher medals."
    }
];
